//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeOrganizer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Category
    {
        public Category()
        {
            this.Recipe_has_Category = new HashSet<Recipe_has_Category>();
        }
        [Key]
        public int category_id { get; set; }
        public string description { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<Recipe_has_Category> Recipe_has_Category { get; set; }
    }
}
