//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeOrganizer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Feedback
    {
        public Feedback()
        {
            this.Media = new HashSet<Media>();
        }
        [Key]
        public int feedback_id { get; set; }
        public int recipe_id { get; set; }
        public int user_id { get; set; }
        public string description { get; set; }
        public string title { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> rating { get; set; }
        public int media_id { get; set; }
        public bool status { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Media> Media { get; set; }
    }
}
