//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeOrganizer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Media
    {
        public Media()
        {
            this.Media_has_Recipe = new HashSet<Media_has_Recipe>();
        }
        
        [Key]
        public int media_id { get; set; }
        public string filelocation { get; set; }
        public int user_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Feedback Feedback { get; set; }
        public virtual ICollection<Media_has_Recipe> Media_has_Recipe { get; set; }
        public virtual User User { get; set; }
    }
}
