//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeOrganizer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Media_has_Recipe
    {
        [Key]
        public int id { get; set; }
        public int recipe_id { get; set; }
        public int media_id { get; set; }
    
        public virtual Media Medium { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
