//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeOrganizer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Recipe
    {
        public Recipe()
        {
            this.Collections = new HashSet<Collection>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Media_has_Recipe = new HashSet<Media_has_Recipe>();
            this.Recipe_has_Category = new HashSet<Recipe_has_Category>();
            this.User_Like_Recipe = new HashSet<User_Like_Recipe>();
        }

        [Key]
        public int recipe_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> media_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date { get; set; }
        public int number_share { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<Collection> Collections { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Media_has_Recipe> Media_has_Recipe { get; set; }
        public virtual ICollection<Recipe_has_Category> Recipe_has_Category { get; set; }
        public virtual ICollection<User_Like_Recipe> User_Like_Recipe { get; set; }
    }
}
